list(
  APPEND
  PROJECT_SOURCES
  ${CMAKE_CURRENT_LIST_DIR}/components/button/button_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/footer/footer1_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/footer/footer2_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/header/header_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/labels/label_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/pages/configuration_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/pages/home_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/pages/informations_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/pages/network_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/components/thermometer/thermometer_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/config/config_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/info/info_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/net/net_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/screens/principal/principal_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/refrigerador_gen.c
  ${CMAKE_CURRENT_LIST_DIR}/ui.c
  ${CMAKE_CURRENT_LIST_DIR}/refrigerador.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_ttf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/fonts/Inter_Bold_otf_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/header_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/subtract_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/thermometer_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/config_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/home_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/info_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/net_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/alert_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/port_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/degelo_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/vent_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/comp_data.c
  ${CMAKE_CURRENT_LIST_DIR}/images/wifi_data.c)